<?php
include_once __DIR__ . '/../vendor/autoload.php';

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Fallback safety if accessed directly without session data payload
if (!isset($_SESSION['ticket_data'])) {
    header('Location: ../index.php');
    exit;
}

// Extract variables from session state context
$ticketData      = array_get_default($_SESSION, 'ticket_data');
$date            = array_get_default($ticketData, 'date');
$userName        = array_get_default($ticketData, 'userName');
$eventName       = array_get_default($ticketData, 'eventName');
$userId          = array_get_default($ticketData, 'userId');
$receiptProducts = array_get_default($ticketData, 'receiptProducts');
$labelsToPrint   = array_get_default($ticketData, 'labelsToPrint');

// Clear the temporary ticket session storage so it doesn't persist on reload
unset($_SESSION['ticket_data']);
?>
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <title>Impression Récolte & Étiquettes</title>
    <style>
        @page {
            size: 80mm auto;
            margin: 0;
        }

        body {
            width: 72mm;
            margin: 0 auto;
            padding: 5mm 0;
            /* Use Calibri as primary, fallback to clean sans-serif */
            font-family: 'Calibri', 'Segoe UI', Arial, sans-serif;
            font-size: 13px;
            color: #000;
        }

        /* Maintain Monospace font only for tabular layouts if needed */
        table {
            width: 95%;
            border-collapse: collapse;
            font-family: 'Calibri', sans-serif;
        }

        .ticket-section {
            width: 100%;
            page-break-after: always;
            box-sizing: border-box;
            padding-bottom: 10px;
            margin-top: 1px;
        }

        .ticket-section:last-child {
            page-break-after: avoid;
        }

        .text-center {
            text-align: center;
        }

        .text-right {
            text-align: right;
        }

        .bold {
            font-weight: bold;
        }

        .line {
            border-bottom: 1px dashed #000;
            margin: 8px 0;
        }

        td {
            padding: 4px 0;
        }

        .barcode {
            margin: 15px 0 5px 0;
            text-align: center;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .barcode svg {
            max-width: 100%;
            height: auto;
        }

        /* Style for product code and prices to match your clear visual layout */
        .code {
            font-family: 'Calibri', sans-serif;
            font-size: 15px;
            font-weight: bold;
            text-align: center;
            margin-bottom: 5px;
        }

        .price-tag {
            font-size: 20px;
            font-weight: bold;
            text-align: center;
            margin: 5px 0;
        }

        /* Target the SVG text elements generated by JsBarcode */
        .barcode svg text {
            font-family: 'Calibri', 'Arial', sans-serif !important;
            font-size: 16px !important;
            font-weight: bold !important;
        }
    </style>
</head>

<body>

    <div class="ticket-section">
        <p class="text-center" style="font-size: 10px;">FANAMARINANA / VOKATRA</p>
        <p class="text-center bold" style="font-size: 14px;"><?= htmlspecialchars(strtoupper($eventName)); ?></p>
        <p class="text-center" style="font-size: 10px;">Daty : <?= htmlspecialchars($date); ?></p>
        <div class="line"></div>

        <p class="text-center bold">Vokatra voaray avy amin'i</p>
        <p class="text-center"><?= htmlspecialchars($userName); ?></p>
        <div class="line"></div>

        <table style="margin-left:5px;">
            <thead>
                <tr class="bold">
                    <td>Vokatra</td>
                    <td class="text-right">Isany</td>
                    <td class="text-right">Vidiny tsirairay</td>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($receiptProducts as $prod): ?>
                    <tr>
                        <td><?= htmlspecialchars($prod['name']); ?></td>
                        <td class="text-right bold">x <?= $prod['qty']; ?></td>
                        <td class="text-right bold"><?= number_format($prod['price'], 0, ',', ' '); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <div class="line"></div>
        <p class="text-center" style="font-size: 10px;">Rosia fanamarinana vokatra</p>
    </div>

    <?php foreach ($labelsToPrint as $label): ?>
        <div class="ticket-section">
            <p class="text-center" style="font-size: 11px; margin: 0;">Etikety ho an'ny vokatra</p>
            <div class="line"></div>

            <div class="code">
                <?= strtoupper(htmlspecialchars($label['product_code'])); ?>
            </div>

            <p class="text-center bold" style="font-size: 20px; margin: 5px 0;">
                <?= strtoupper(htmlspecialchars($label['name'])); ?>
            </p>

            <p class="text-center price-tag">
                <?= number_format($label['price'], 0, '.', ' '); ?> MGA
            </p>


            <div class="line"></div>

            <div class="code">
                <?= strtoupper(htmlspecialchars($label['product_code'])); ?>
            </div>

            <p class="text-center bold" style="font-size: 20px; margin: 5px 0;">
                <?= strtoupper(htmlspecialchars($label['name'])); ?>
            </p>

            <p class="text-center price-tag">
                <?= number_format($label['price'], 0, '.', ' '); ?> MGA
            </p>

            <div class="barcode">
                <svg class="barcode-generator" data-value="<?= $label['barcode']; ?>"></svg>
            </div>
        </div>
    <?php endforeach; ?>

    <script src="../../assets/js/JsBarcode.all.min.js"></script>
    <script>
        window.onload = function() {
            const barcodeElements = document.querySelectorAll('.barcode-generator');

            barcodeElements.forEach(function(el) {
                const barcodeValue = el.getAttribute('data-value');

                try {
                    JsBarcode(el, barcodeValue, {
                        format: "EAN13",
                        width: 2,
                        height: 70,
                        displayValue: true,
                        font: "calibri",
                        fontSize: 15,
                        textMargin: 2,
                        background: "#ffffff"
                    });
                } catch (error) {
                    console.error("Error generating barcode: " + barcodeValue, error);
                    el.parentElement.innerHTML = "<span style='color:red; font-weight:bold;'>[Barcode Error]</span>";
                }
            });

            setTimeout(function() {
                window.print();
            }, 300);
        }
    </script>
</body>

</html>